### PR TITLE
Update MMM-MicrosoftToDo.js

### PR DESCRIPTION
**Pull request by ftenkley**
Added code to create a fade effect on the list. Takes 2 parameters from config.js: fade (True or False) and fadePoint (between 0 and 1) to set the starting point of the fade. Code was modified from the MMM-nstreinen module by @qistoph.

### CODE REVIEW

**Comment by thobach** [comment]
Thanks @ftenkley for your contribution. Could you please take a look at the code issues that were detected by eslint in https://travis-ci.com/github/thobach/MMM-MicrosoftToDo/builds/199271473 and address these as well? Thanks!

**Comment by ftenkley** [comment]
@thobach, I fixed the issues that were detected by eslint and did a new commit. Are there any further steps I should take so you can implement the change?

**Comment by thobach** [comment]
@ftenkley I'm sorry, but there seem to be still a few small issues that block the merge: https://travis-ci.com/github/thobach/MMM-MicrosoftToDo/builds/201753983#L215. Could you please take a look at them as well? Thanks!

**Comment by thobach** [comment]
Thanks @ftenkley for your nice contribution. Could I please ask you for one more favor and add the description of the new config parameters to the README.MD file? Thanks1

**Comment by thobach** [comment]
Thanks @ftenkley for your contribution. I merged your pull request and tested the feature. I noticed just two small things that you may want to optimize or fix:
* the documentation of the fade parameter doesn't mention the dependency on the itemLimit parameter
* the last item is hidden as the opacity is 0, I suggest to let the opacity not go below 0.2 to ensure it is still somewhat visible

**Pull request merged**
